<?php
	#modulesForLaterUse.php	
	$loggedIn =  false;
?>
<!DOCTYPE html>
<html>
	<head>
		<meta http-equiv="content-type" content="text/html; charset=UTF-8">
		<meta name="author" content="Marcian Diamond">
		<title>SCVWD Flood Forecast System</title>
		<link rel="shortcut icon" href="assets/images/favicon.ico">
		<!--stylesheets -->
    	<link rel="stylesheet" href="assets/css/OL/theme/default/style.css" type="text/css">
		<link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
    	<link rel="stylesheet" href="//code.jquery.com/ui/1.10.4/themes/smoothness/jquery-ui.css">
		<link rel="stylesheet" href="assets/css/custom.css" type="text/css">
	</head>
	<body onload="init()">
		<div id="disclaimer-message" title="Disclaimer" style="display:none;width:400px;">
			<span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 0 0;"></span>
			<p>
				The flood forecasts and predicted inundation areas are generated by the Santa Clara Water District using data collected from multiple other sources, including the National Weather Service. As with all weather forecasts, information is not guaranteed to be accurate, current or complete, and the tools used to predict the flooding areas are not guaranteed to be accurate either. Therefore, this website is designed as an informational tool to aid in disaster preparation. Information is provided as-is, and the use of the data provided by this website is solely at your own risk.
			</p>
			<p>
				Recommended browsers: Google Chrome, Mozilla Firefox
			</p>
		</div>
		<div id="myNav">
				<div id="logo" style="display:inline;margin-left:10px;">
					<a href="http://www.valleywater.org">
						<img id="imgLogo" src="assets/images/logo.gif" height="48" width="219">
					</a>
				</div>
				<div class="pull-right" style="display:inline!important; margin-top:10px;">
					<span class="glyphicon glyphicon-search" title="View Select" style="display:inline;">&nbsp</span>
					<select id="sbGageSelect" class="form-control" style="display:inline;width:135px;margin-right:25px;">
				  		<option selected="selected" disabled="disabled" value="default">Gage Select</option>
				  		<option value="ForecastStreamFlow.1">Ross Ck. at Cherry Ave.</option>
						<option value="ForecastStreamFlow.2">Upper Guadalupe above Branham Ln.</option>
						<option value="ForecastStreamFlow.4">West Little Llagas blw Edmundson Ave.</option>
						<option value="ForecastStreamFlow.3">San Francisquito CK. at Stanford</option>
					</select>
					<span class="glyphicon glyphicon-eye-open" title="View Select" style="display:inline;">&nbsp</span>
					<select id="sbViewSelect" class="form-control" style="display:inline;width:125px;margin-right:25px;">
				  		<option selected="selected" disabled="disabled" value="default">View Select</option>
				  		<option value="county">County</option>
						<option value="losAltos">Los Altos</option>
						<option value="milpitas">Milpitas</option>
						<option value="paloAlto">Palo Alto</option>
						<option value="sanJose">San Jose</option>
						<option value="santaClara">Santa Clara</option>
						<option value="sunnyvale">Sunnyvale</option>
					</select>
				</div>
		</div><!--end navbar-->
		<div id="map"></div>
		<!-- hide mouseposition, position only used for tooltips -->
		<div id="mousePosition" style="visibility:hidden;"></div>
		<!-- popup div for tooltips over forecast gages -->
		<div class="popup" id="tooltip" style="visibility: hidden;"></div>
		<div id="helpBox" style="display:none;z-index: 2000;">
			<span id='closeHelpBox' title='close'>X</span>
			<p id="helpBoxText"></p>
			<!-- <p><a id="closeHelpBox" style="cursor:pointer;">[close]</a></p> -->
		</div>
		<!--flood forecast gage information in jQuery UI tabs -->
		<div id="qpfControls">
			<ul>
				<li><a href="#qpfTab">QPF</a></li>
			</ul>
			<div id="qpfTab">
				<div id="qpf-scale"></div>
				<div id="qpf-date"></div>
		        <div id="qpf-slide"></div>
		        <div id="qpf-value"></div>
			</div>
		</div>
		<div id="forecastInfo">
			<ul>
				<li><a href="#fc-tabs-1">Flood Forecast Information</a></li>
				<li><a href="#tabGageDetails">Gage Details</a></li>
				<li><a href="#fc-tabs-3">1% Flood Demo</a></li>
				<li><a href="#fc-tabs-4">ALERT Me</a></li>
				<!-- todo add slide down/up button functionality to hide tabbed pane -->
				<!-- <li style="margin-left:50px;">Test</li> -->
			</ul>
			<div id="fc-tabs-1" style="white-space: nowrap;">
					<div id="fcPlot">
						loading hydrograph...<img src='assets/images/ajax-loader.gif'/>
					</div>
			</div>
			<div id="tabGageDetails">
				 <table id="tblGageDetails" class="table table-bordered table-striped table-hover">
				 	<tr>
				 		<td>
				 			<strong>Station Name</strong>
				 		</td>
				 		<td id="gd_staName"></td>
				 	</tr>
				 	<tr>
				 		<td>
				 			<strong>Station Number</strong>
				 		</td>
				 		<td id="gd_staNum"></td>
				 	</tr>
				 	<tr>
				 		<td>
				 			<strong>Alert ID</strong>
				 		</td>
				 		<td id="gd_alertID"></td>
				 	</tr>
				 	<tr>
				 		<td>
				 			<strong>Gage Type</strong>
				 		</td>
				 		<td id="gd_gageType"></td>
				 	</tr>
				 	<tr>
				 		<td>
				 			<strong>Major Watershed</strong>
				 		</td>
				 		<td id="gd_majorWatershed"></td>
				 	</tr>
				 	<tr>
				 		<td>
				 			<strong>Longitude</strong>
				 		</td>
				 		<td id="gd_longitude"></td>
				 	</tr>
				 	<tr>
				 		<td>
				 			<strong>Latitude</strong>
				 		</td>
				 		<td id="gd_latitude"></td>
				 	</tr>
				 </table>
			</div>
			<div id="fc-tabs-3">
				<div class="row">
					<div class="col-md-12" style="display:inline;">
						<div id="demoControls" style="display:inline;">
							<p><strong>Please Select Flood Event</strong><img id='floodEventHelpIcon' style="margin-left:10px;" src="assets/images/helpIcon15px.png"/></p>
							<hr/>
							<select id ="floodDemoSelect" class="form-control" style="width:200px;display:inline;">
								<option value="default" selected="selected" disabled="disabled">Choose...</option>
								<option value="2year">50% (2 year)</option>
								<option value="5year">20% (5 year)</option>
								<option value="10year">10% (10 year)</option>
								<option value="25year">4% (25 year)</option>
								<option value="50year">2% (50 year)</option>
								<option value="100year">1% (100 year)</option>
							</select>
						</div>
						<button class="btn btn-primary" id="btnClearDemoSpill" disabled style="display:inline;margin-left:20px;margin-bottom:5px;">Clear Spill Layer</button>
					</div>
				</div>
			</div>
			<div id="fc-tabs-4">
				<!--Alert Me functionality in external file-->
			</div>
		</div>
		<!--load scripts at end of page -->
		<!--google maps, openlayers, proj4js -->
		<script src="http://maps.google.com/maps/api/js?v=3&amp;sensor=false&amp;key=AIzaSyB7Ndq60bsM6G2DvKY7SGEbf7vsSa_2Eg8"></script>
		<script src="http://openlayers.org/api/OpenLayers.js"></script>
    	<script src="//cdnjs.cloudflare.com/ajax/libs/proj4js/2.2.2/proj4-src.js"></script>

    	<!--jQuery, jQueryUI, bootstrap, highcharts-->
		<script src="//code.jquery.com/jquery-1.11.0.min.js"></script>
		<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
		<script src="//code.jquery.com/ui/1.10.4/jquery-ui.js"></script>
		<script src="//code.highcharts.com/highcharts.js"></script>
		<script src="//cdnjs.cloudflare.com/ajax/libs/d3/3.4.11/d3.min.js"></script>
		
		<!--application specific scripts -->
		<!--<script src="http://166.78.145.195/qpfserve/qpfserve.js"></script>-->
		<script src="assets/js/plots/flowData.js"></script>
		<script src="assets/js/scvwdflood.js"></script>
		<script src="assets/js/streamFlowGages.js"></script>
		</script>
	</body>
</html>